extraVolumes: |
  - name: realm-secret
    secret:
      secretName: realm-secret

extraVolumeMounts: |
  - name: realm-secret
    mountPath: "/realm/"
    readOnly: true

extraEnv: |
  - name: KEYCLOAK_IMPORT
    value: /realm/realm.json

pgchecker:
  resources:
    requests:
      cpu: '20m'
      memory: '32Mi'
    limits:
      cpu: '20m'
      memory: '32Mi'
